import os

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

MOTOR_LEFT_PORT = 'outB'
MOTOR_RIGHT_PORT = 'outC'
SENSOR_COLOR_PORT = 'in1'
SENSOR_ULTRASONIC_PORT = 'in2'

SPEED_DEFAULT = 30
SPEED_SLOW = 15
SPEED_FAST = 50

WHEEL_DIAMETER_MM = 56
WHEEL_TRACK_MM = 120

LINE_THRESHOLD = 30
OBSTACLE_THRESHOLD_CM = 20

ALPHA = 0.1
GAMMA = 0.9
EPSILON = 1.0
EPSILON_MIN = 0.01
EPSILON_DECAY = 0.995

NUM_STATES = 3
NUM_ACTIONS = 4

EPISODES = 200
EPISODE_TIMEOUT = 30

QTABLE_FILE = os.path.join(PROJECT_DIR, 'qtable.json')

STATE_ON_LINE = 0
STATE_OFF_LINE = 1
STATE_OBSTACLE = 2

ACTION_FORWARD = 0
ACTION_REVERSE = 1
ACTION_TURN_LEFT = 2
ACTION_TURN_RIGHT = 3

ACTION_NAMES = ['FORWARD', 'REVERSE', 'TURN_LEFT', 'TURN_RIGHT']

REWARD_ON_LINE = 10
REWARD_SMOOTH = 5
REWARD_CORRECT_TURN = 5
REWARD_FAST_PROGRESS = 10
REWARD_LOST_LINE = -10
REWARD_WRONG_MOVE = -5
REWARD_COLLISION = -100
